const CardData = () => {
  return [
    {
      name: "CHELSEA BOOTS",
      category: "Shoes",
      price: "$3450",
      imageSrc:
        "https://i.ibb.co/8MVqWdX/917690013999-DS-234c6a41-c0ef-4d1.png",
      rating: 4.5,
    },
    {
      name: "Walker Leather Office Travel Bag",
      category: "Bags",
      price: "$2440",
      imageSrc: "https://i.ibb.co/16096fr/images.png",
      rating: 4.8,
    },
    {
      name: "Grease leather belt nature",
      category: "Belt",
      price: "$219",
      imageSrc: "https://i.ibb.co/F0312DL/grease-leather-belt-nature.png",
      rating: 4.5,
    },
    {
      name: "Original Premium Leather Gents Wallet",
      category: "Wallets",
      price: "$420",
      imageSrc: "https://i.ibb.co/HrPPkRr/leather-wallet.png",
      rating: 3.6,
    },
    {
      name: "Black PU Lather Jacket For Men",
      category: "Jacket",
      price: "$1099",
      imageSrc: "https://i.ibb.co/5M24jfX/07cc2082a1b550339e3c0cc7e581259d.png",
      rating: 4.2,
    },
    {
      name: "CLASSIC WINGTIP SHOES",
      category: "Shoes",
      price: "$7550",
      imageSrc: "https://i.ibb.co/MZzKXLG/red-leather-shoes-stand-light-wo.png",
      rating: 4.8,
    },
    {
      name: "Ferragamo Black Leather Belt for Men",
      category: "Belt",
      price: "$35",
      imageSrc: "https://i.ibb.co/rpz36HM/7baaf698ae9b8e8c23f76830cd4c7716.png",
      rating: 4.7,
    },
    {
      name: "SK31C SKMEI Luxury Business Leather Watch",
      category: "Watch",
      price: "$2100",
      imageSrc: "https://i.ibb.co/qxwK5N4/SK31-C-510x510.png",
      rating: 4.2,
    },

    {
      name: "Genuine Leather Long Hand Wallet",
      category: "Wallets",
      price: "$1700",
      imageSrc: "https://i.ibb.co/0VWYWt8/R1038-7-510x510.png",
      rating: 4.1,
    },
    {
      name: "BRAIDED MOCCASINS",
      category: "Shoes",
      price: "$2450",
      imageSrc: "https://i.ibb.co/6Y70Phy/custom-resized-424a9ffe-e798-461.png",
      rating: 4.0,
    },

    {
      name: "BUCKLED LOAFER",
      category: "Loafers",
      price: "$2115",
      imageSrc: "https://i.ibb.co/qFcf5hZ/145-eaf02730-5e63-4023-9883-a39b.png",
      rating: 4.9,
    },

    {
      name: "PLAIN LOAFERS",
      category: "Loafers",
      price: "$21",
      imageSrc: "https://i.ibb.co/fpMKG82/custom-resized-ff5bfd43-2f14-48c.png",
      rating: 4.0,
    },

    {
      name: "Handmade Leather Slide Sandals With Metal Ring",
      category: "Sandals",
      price: "1660",
      imageSrc: "https://i.ibb.co/VjKfxH5/259a147b9d1b0743c7275a43d8320f05.png",
      rating: 4.6,
    },
    {
      name: "Classic Brown Braided Leather Bracelet",
      category: "Bracelet",
      price: "$48",
      imageSrc: "https://i.ibb.co/3vJNRd2/images-3.png",
      rating: 3.5,
    },
    {
      name: "B524 bekeleBOLO Genuine Leather Automatic Buckle Belt",
      category: "Belt",
      price: "$1220",
      imageSrc: "https://i.ibb.co/rv0Xqyt/a6ecf9d44effba5fecdca4c2f2c4128d.png",
      rating: 4.3,
    },
    {
      name: "BLACK Wide Strap Slip on Sandals",
      category: "Sandals",
      price: "$2550",
      imageSrc: "https://i.ibb.co/TKwQ9DF/handmade-leather-wide-strap-slip.png",
      rating: 3.9,
    },
    {
      name: "Bag Leather Duffel Travel Men",
      category: "Bags",
      price: "$3100",
      imageSrc: "https://i.ibb.co/ScWTt3K/images-1.png",
      rating: 4.0,
    },
    {
      name: "Ultra Premium Wallet",
      category: "Wallets",
      price: "$3550",
      imageSrc:
        "https://i.ibb.co/TLP8BY1/O1-CN01-Kaj-Xi32-Lx-Ddxv-Rj-Rk-28498897.png",
      rating: 4.8,
    },
    {
      name: "Cartelo Branded Leather Belt",
      category: "Belt",
      price: "$32.99",
      imageSrc: "https://i.ibb.co/dLZWkZh/15-1.png",
      rating: 4.5,
    },
    {
      name: "Pink Sneakers For women For Casual use",
      category: "Shoes",
      price: "1650",
      imageSrc: "https://i.ibb.co/xsXYzkd/7592d001b3a88fb8be1172ba44419840.png",
      rating: 4.1,
    },
    {
      name: "BENI BELT",
      category: "Belt",
      price: "$19",
      imageSrc: "https://i.ibb.co/xMQ9vCQ/S0206c0a1b9954baa9ff27c37444aa0c.png",
      rating: 4.2,
    },
    {
      name: "EF smart ladies heels sandal",
      category: "Sandals",
      price: "$29",
      imageSrc: "https://i.ibb.co/1RhNVHV/1c4417baedaa5dde1eeea989b3ac6501.png",
      rating: 4.3,
    },
    {
      name: "Cow Leather Laptop Bag SB-LB454",
      category: "Bags",
      price: "$4550",
      imageSrc: "https://i.ibb.co/7z2hxY2/Cow-Leather-Laptop-Bag-SB-LB454.png",
      rating: 4.0,
    },
    {
      name: "ORAS Genuine Leather Ladies Purse",
      category: "Wallets",
      price: "$1299",
      imageSrc: "https://i.ibb.co/fDMTzqB/RA69-M-3-510x510.png",
      rating: 4.7,
    },
    {
      name: "Leather Jacket for men",
      category: "Jacket",
      price: "$7100",
      imageSrc: "https://i.ibb.co/bNZ640v/samo-puja-2023-ot-26-9b05.png",
      rating: 3.6,
    },
    {
      name: "Genuine-leather-loafer",
      category: "Loafers",
      price: "$2150",
      imageSrc: "https://i.ibb.co/Yjp7yZL/genuine-leather-loafer-for-men-l.png",
      rating: 4.4,
    },
    {
      name: "Leather formal Belt for Men Black",
      category: "Belt",
      price: "$550",
      imageSrc: "https://i.ibb.co/r3DrYSw/6ba346ddda04a2745921f1d2f811dfbf.png",
      rating: 3.5,
    },
    {
      name: "Leather-Mens-Leather-Sandal",
      category: "Sandals",
      price: "$999",
      imageSrc: "https://i.ibb.co/MRMHvBf/SSB-Leather-Mens-Leather-Sandal.png",
      rating: 4.9,
    },
    {
      name: "Classic Backpack SB-BP138",
      category: "Bags",
      price: "$7450",
      imageSrc: "https://i.ibb.co/NyBhYjz/Classic-Backpack-SB-BP138.png",
      rating: 3.7,
    },
    {
      name: "The Seiko Alpinist SPB117 - 9GAG",
      category: "Watch",
      price: "$1440",
      imageSrc: "https://i.ibb.co/bbrRD27/a-R7-Rob-M-460s.png",
      rating: 4.5,
    },
    {
      name: "Mens-Leather-Executive-Bag",
      category: "Bags",
      price: "$5999",
      imageSrc: "https://i.ibb.co/9vGxKRR/Mens-Leather-Executive-Bag-SB-LB.png",
      rating: 4.1,
    },

    {
      name: "PATENT TASSEL MOCCASINS",
      category: "Shoes",
      price: "$3499",
      imageSrc: "https://i.ibb.co/znbwc3R/938190014499-A-700x.png",
      rating: 4.2,
    },

    {
      name: "Amber-Padded-Italian",
      category: "Watch",
      price: "$1899",
      imageSrc: "https://i.ibb.co/yyXJ0hz/20mm-Amber-Padded-Italian-Vintag.png",
      rating: 4.2,
    },
    {
      name: "Brown Leather Formal Belt For Men",
      category: "Belt",
      price: "$250",
      imageSrc: "https://i.ibb.co/6vmcRLb/b7feff36334be47319a971caedc40cb5.jpg",
      rating: 3.8,
    },
    {
      name: "Mens-Leather-Sandal",
      category: "Sandals",
      price: "$799",
      imageSrc: "https://i.ibb.co/p4Vb2RT/Mens-Leather-Sandal-SB-S528-3.png",
      rating: 4.1,
    },
    {
      name: "Black Plane Leather Executive Bag SB-LB442",
      category: "Bags",
      price: "$5999",
      imageSrc: "https://i.ibb.co/DtMNw7Q/Black-Plane-Leather-Executive-Ba.png",
      rating: 4.6,
    },
    {
      name: "Fossil Townsman Men's Watch with Chronograph Display and Genuine Leather Band",
      category: "Watch",
      price: "$3499",
      imageSrc: "https://i.ibb.co/5vvcwq7/71b5-Mt-Bv-L6-L-AC-UL320.png",
      rating: 3.5,
    },
    {
      name: "CURREN 8314 Casual Waterproof Watch",
      category: "Watch",
      price: "$1199",
      imageSrc: "https://i.ibb.co/JcP0Qcz/CURREN-8314-Casual-Waterproof-Wa.png",
      rating: 4.3,
    },
    {
      name: "Premium-Leather-Slip-On-Shoe",
      category: "Shoes",
      price: "$1599",
      imageSrc: "https://i.ibb.co/9nLHQzW/AAJ-Premium-Leather-Slip-On-Shoe.png",
      rating: 3.9,
    },
    {
      name: "Islamic Silicone Bracelet",
      category: "Bracelet",
      price: "$299",
      imageSrc: "https://i.ibb.co/hRtYpr9/C183-1-247x247.png",
      rating: 4.0,
    },
    {
      name: "Product 51",
      category: "Sandals",
      price: "$33.50",
      imageSrc: "https://i.ibb.co/yVTt0Dw/3.png",
      rating: 4.8,
    },
    {
      name: "PLAIN LOAFERS",
      category: "Loafers",
      price: "$2815",
      imageSrc: "https://i.ibb.co/LCQ60Jc/custom-resized-4082d9a2-d40e-454.png",
      rating: 3.7,
    },
    {
      name: "SSB Leather GYM Bag SB-GM02",
      category: "Bags",
      price: "$5599",
      imageSrc: "https://i.ibb.co/vQwY4sm/SSB-Leather-GYM-Bag-SB-GM02-A.png",
      rating: 3.6,
    },
    {
      name: "Black-Leather-Wallet",
      category: "Wallets",
      price: "$650",
      imageSrc: "https://i.ibb.co/Gdj1YLB/Black-Leather-Card-Holder-SB-W12.png",
      rating: 4.5,
    },
    {
      name: "Maroon-Gradient-Messenger-Bag",
      category: "Bags",
      price: "$69.99",
      imageSrc: "https://i.ibb.co/PxQzBgZ/Maroon-Gradient-Messenger-Bag-SB.png",
      rating: 4.3,
    },
    {
      name: "CURREN-R2-S-Unisex-Smartwatch",
      category: "Watch",
      price: "$1799",
      imageSrc:
        "https://i.ibb.co/wgMmNVj/CURREN-R2-S-Unisex-Smartwatch-IP6.png",
      rating: 4.7,
    },
    {
      name: "Set Vintage hand-woven Bracelet for Men",
      category: "Bracelet",
      price: "$499",
      imageSrc: "https://i.ibb.co/YcyFnfB/C139-510x510.png",
      rating: 4.2,
    },
    {
      name: "AUTOGRAPH LEO W",
      category: "Shoes",
      price: "$2999",
      imageSrc: "https://i.ibb.co/3pCdwRq/219587-1-PL-01.png",
      rating: 4.9,
    },
    {
      name: "Floral Design Ladies Handbag SB-HB539",
      category: "Bags",
      price: "$3699",
      imageSrc: "https://i.ibb.co/rt4YP21/2-1.png",
      rating: 3.7,
    },
    {
      name: "PLAIN HALF LOAFERS",
      category: "Loafers",
      price: "$6290",
      imageSrc: "https://i.ibb.co/6BGg0Ht/130-736ad026-971e-49c5-87fb-ae57.png",
      rating: 4.6,
    },
    {
      name: "Set Vintage hand-woven Bracelet for Men",
      category: "Bracelet",
      price: "$450",
      imageSrc: "https://i.ibb.co/2qjHPtT/C136-510x508.png",
      rating: 3.8,
    },
    {
      name: "Men's Navy Multi-Sport Jacket",
      category: "Jacket",
      price: "$2999",
      imageSrc: "https://i.ibb.co/ccVnwzw/217364-1-CI-0979.png",
      rating: 4.6,
    },
    {
      name: "Set believe rope retro braided Bracelet for Men",
      category: "Bracelet",
      price: "$59.99",
      imageSrc: "https://i.ibb.co/8XHW5G6/C132-510x510.png",
      rating: 4.0,
    },
    {
      name: "Oxford Whole Cut Shoes",
      category: "Shoes",
      price: "$4990",
      imageSrc:
        "https://i.ibb.co/wQ0xVGd/128-8c19efb6-491d-4b58-84c4-af3e-1.png",
      rating: 3.8,
    },
    {
      name: "Canvas Hot Tactical Casual Plastic Black Buckle",
      category: "Belt",
      price: "$399",
      imageSrc: "https://i.ibb.co/3hkCQPV/edc8dc98da3d5ca89d3a89085332f12b.png",
      rating: 3.9,
    },
    {
      name: "Mens-Leather-Sandal",
      category: "Sandals",
      price: "$899",
      imageSrc: "https://i.ibb.co/sFm4zRW/Mens-Leather-Sandal-SB-S528-2.png",
      rating: 4.1,
    },
    {
      name: "Distressed-Leather-Duffle-Bag",
      category: "Bags",
      price: "$9999",
      imageSrc: "https://i.ibb.co/Y45FNFw/Distressed-Leather-Duffle-Bag-SB.png",
      rating: 4.5,
    },
    {
      name: "Antique Brown ( Agun ) Short Leather Wallet",
      category: "Wallets",
      price: "$999",
      imageSrc: "https://i.ibb.co/GtS8BG9/Antique-Brown-Agun-Short-Leather.png",
      rating: 3.5,
    },
    {
      name: "Brown PU Lather Jacket For Men",
      category: "Jacket",
      price: "$1599",
      imageSrc: "https://i.ibb.co/PQ7j9w3/6c0a9804afd778d0e01ca1fc6ba4f39c.png",
      rating: 4.4,
    },
    {
      name: "TRENDY LOAFER",
      category: "Loafers",
      price: "$79",
      imageSrc:
        "https://i.ibb.co/w4rPRbQ/902690113199-DS-07571dba-53a5-488.png",
      rating: 4.5,
    },
    {
      name: " Handmade Biblical Leather Sandals",
      category: "Sandals",
      price: "$3499",
      imageSrc: "https://i.ibb.co/hWxZM8D/images-2.png",
      rating: 4.7,
    },

    {
      name: "BUCKLED LOAFER",
      category: "Shoes",
      price: "$3250",
      imageSrc: "https://i.ibb.co/DYbX3LY/157-700x.png",
      rating: 4.3,
    },

    {
      name: "Front Adjustable Sandals",
      category: "Sandals",
      price: "$2299",
      imageSrc: "https://i.ibb.co/R6RqPkc/x-strap-front-adjustable-handmad.png",
      rating: 3.8,
    },
    {
      name: "Multifunctional Long Leather Wallet",
      category: "Wallets",
      price: "$1499",
      imageSrc: "https://i.ibb.co/T2B5LjL/Multifunctional-Long-Leather-Wal.png",
      rating: 4.1,
    },

    {
      name: "lotto-black-neL",
      category: "Shoes",
      price: "$3499",
      imageSrc: "https://i.ibb.co/9cZQZ1T/7-f21r5759-070-7-lotto-black-neo.png",
      rating: 4.0,
    },
    {
      name: "White-Plaited-Leather-Belt",
      category: "Belt",
      price: "$1499",
      imageSrc: "https://i.ibb.co/x56Prsg/White-Plaited-Leather-Belt-SB-B6.png",
      rating: 4.4,
    },
    {
      name: "PREMIUM LEATHER FORMALS",
      category: "Shoes",
      price: "$4990",
      imageSrc: "https://i.ibb.co/LkVJs2Q/935190035999-A-700x.png",
      rating: 3.9,
    },
    {
      name: "Plaited-Leather-Belt",
      category: "Belt",
      price: "$1549",
      imageSrc: "https://i.ibb.co/QcmJVRw/Plaited-Leather-Belt-SB-B66-4.png",
      rating: 4.8,
    },
    {
      name: "EMBOSSED OXFORD SHOES",
      category: "Shoes",
      price: "$2170",
      imageSrc: "https://i.ibb.co/gdgKT5Z/918190233499-A-700x.png",
      rating: 4.7,
    },
    {
      name: "VIBRANT CRYSTAL ORCHID LADIES SUMMER",
      category: "Sandals",
      price: "$1299",
      imageSrc: "https://i.ibb.co/vv0Zxpx/5405013-7-500x.png",
      rating: 3.6,
    },
    {
      name: "Black-Leather-Tote-Bag",
      category: "Bags",
      price: "$3499",
      imageSrc: "https://i.ibb.co/cLKKZwD/Black-Leather-Tote-Bag-SB-LG208.png",
      rating: 4.1,
    },
    {
      name: "MEN COMFY WALK LEATHER TOEPOST",
      category: "Shoes",
      price: "$1699",
      imageSrc: "https://i.ibb.co/2SZ0N1z/84460241-500x.png",
      rating: 4.9,
    },
    {
      name: "MEN LEATHER GEAR BELT",
      category: "Belt",
      price: "$699",
      imageSrc: "https://i.ibb.co/qxnHKRy/93450432-500x.png",
      rating: 4.7,
    },
    {
      name: "Lightweight Outdoors For Men  (Olive)",
      category: "Shoes",
      price: "$2299",
      imageSrc: "https://i.ibb.co/WgHY5z9/6-faf4-6-furo-olive-original-ima.png",
      rating: 4.2,
    },
    {
      name: "Genuine Leather Belt for Men",
      category: "Belt",
      price: "$499",
      imageSrc: "https://i.ibb.co/XbJnCR0/b164-1-510x510.png",
      rating: 3.8,
    },
    {
      name: "MC3 Megir Blue Chronograph",
      category: "Watch",
      price: "$3099",
      imageSrc: "https://i.ibb.co/FHtPX4F/MC3-510x510.png",
      rating: 4.6,
    },
    {
      name: "Genuine-Leather-Executive-Bag",
      category: "Bags",
      price: "$7699",
      imageSrc: "https://i.ibb.co/jg24VTq/Genuine-Leather-Executive-Bag-SB.png",
      rating: 4.5,
    },
    {
      name: "WA85N JEEP Genuine Leather Wallet",
      category: "Wallets",
      price: "$1300",
      imageSrc: "https://i.ibb.co/mXKS5d1/WA85-N-2-510x510.png",
      rating: 4.0,
    },
    {
      name: "EMBOSSED OXFORD SHOES",
      category: "Shoes",
      price: "$4950",
      imageSrc: "https://i.ibb.co/kxq885Y/118-2ebfee83-14c6-4ae8-9aab-691d.png",
      rating: 3.5,
    },

    {
      name: "Plain Loafers",
      category: "Loafers",
      price: "$1559",
      imageSrc: "https://i.ibb.co/52CZp7w/150-700x.png",
      rating: 4.4,
    },
    {
      name: "Men’s Breathable Running Shoes: White Mesh Casual Sneakers",
      category: "Shoes",
      price: "$2799",
      imageSrc: "https://i.ibb.co/mcbk558/Z1013-5-510x510.png",
      rating: 4.4,
    },
    {
      name: "Aaj-Leather-Executive-Bag",
      category: "Bags",
      price: "$5299",
      imageSrc: "https://i.ibb.co/jZtgQ7n/Aaj-Leather-Executive-Bag-SB-LB4.png",
      rating: 4.6,
    },
    {
      name: "PREMIUM LEATHER FORMALS",
      category: "Shoes",
      price: "$4999",
      imageSrc: "https://i.ibb.co/F7ktYRW/934190035999-ST-600x.png",
      rating: 4.1,
    },
    {
      name: "Oil-Pull-Up-Leather-Duffle-Bag",
      category: "Bags",
      price: "$11990",
      imageSrc: "https://i.ibb.co/RYJx1FH/Oil-Pull-Up-Leather-Duffle-Bag-S.png",
      rating: 4.7,
    },
  ];
};

export default CardData;
