const CardData = () => {
  return [
    {
      id: 1,
      name: "CHELSEA BOOTS",
      category: "Shoes",
      previousPrice: "4000৳",
      previousPrice: "4000৳",
      price: "3450৳",
      imageSrc:
        "https://i.ibb.co/8MVqWdX/917690013999-DS-234c6a41-c0ef-4d1.png",
      rating: 4.5,
    },
    {
      id: 2,
      name: "Walker Leather Office Travel Bag",
      category: "Bags",
      previousPrice: "2850৳",
      price: "2440৳",
      imageSrc: "https://i.ibb.co/16096fr/images.png",
      rating: 4.8,
    },
    {
      id: 3,
      name: "Grease leather belt nature",
      category: "Belt",
      previousPrice: "250৳",
      price: "219৳",
      imageSrc: "https://i.ibb.co/F0312DL/grease-leather-belt-nature.png",
      rating: 4.5,
    },
    {
      id: 4,
      name: "Original Premium Leather Gents Wallet",
      category: "Wallets",
      previousPrice: "500৳",
      price: "420৳",
      imageSrc: "https://i.ibb.co/HrPPkRr/leather-wallet.png",
      rating: 3.6,
    },
    {
      id: 5,
      name: "Black PU Lather Jacket For Men",
      category: "Jacket",
      previousPrice: "1290৳",
      price: "1099৳",
      imageSrc: "https://i.ibb.co/5M24jfX/07cc2082a1b550339e3c0cc7e581259d.png",
      rating: 4.2,
    },
    {
      id: 6,
      name: "CLASSIC WINGTIP SHOES",
      category: "Shoes",
      previousPrice: "7990৳",
      price: "7550৳",
      imageSrc: "https://i.ibb.co/MZzKXLG/red-leather-shoes-stand-light-wo.png",
      rating: 4.8,
    },
    {
      id: 7,
      name: "Ferragamo Black Leather Belt for Men",
      category: "Belt",
      previousPrice: "150৳",
      price: "135৳",
      imageSrc: "https://i.ibb.co/rpz36HM/7baaf698ae9b8e8c23f76830cd4c7716.png",
      rating: 4.7,
    },
    {
      id: 8,
      name: "SK31C SKMEI Luxury Business Leather Watch",
      category: "Watch",
      previousPrice: "2450৳",
      price: "2100৳",
      imageSrc: "https://i.ibb.co/qxwK5N4/SK31-C-510x510.png",
      rating: 4.2,
    },

    {
      id: 9,
      name: "Genuine Leather Long Hand Wallet",
      category: "Wallets",
      previousPrice: "1990৳",
      price: "1700৳",
      imageSrc: "https://i.ibb.co/0VWYWt8/R1038-7-510x510.png",
      rating: 4.1,
    },
    {
      id: 10,
      name: "BRAIDED MOCCASINS",
      category: "Shoes",
      previousPrice: "2750৳",
      price: "2450৳",
      imageSrc: "https://i.ibb.co/6Y70Phy/custom-resized-424a9ffe-e798-461.png",
      rating: 4.0,
    },

    {
      id: 11,
      name: "BUCKLED LOAFER",
      category: "Loafers",
      previousPrice: "2390৳",
      price: "2115৳",
      imageSrc: "https://i.ibb.co/qFcf5hZ/145-eaf02730-5e63-4023-9883-a39b.png",
      rating: 4.9,
    },

    {
      id: 12,
      name: "PLAIN LOAFERS",
      category: "Loafers",
      previousPrice: "2400৳",
      price: "2190৳",
      imageSrc: "https://i.ibb.co/fpMKG82/custom-resized-ff5bfd43-2f14-48c.png",
      rating: 4.0,
    },

    {
      id: 13,
      name: "Handmade Leather Slide Sandals With Metal Ring",
      category: "Sandals",
      previousPrice: "1950৳",
      price: "1660৳",
      imageSrc: "https://i.ibb.co/VjKfxH5/259a147b9d1b0743c7275a43d8320f05.png",
      rating: 4.6,
    },
    {
      id: 14,
      name: "Classic Brown Braided Leather Bracelet",
      category: "Bracelet",
      previousPrice: "210৳",
      price: "180৳",
      imageSrc: "https://i.ibb.co/3vJNRd2/images-3.png",
      rating: 3.5,
    },
    {
      id: 15,
      name: "B524 bekeleBOLO Genuine Leather Automatic Buckle Belt",
      category: "Belt",
      previousPrice: "1370৳",
      price: "1220৳",
      imageSrc: "https://i.ibb.co/rv0Xqyt/a6ecf9d44effba5fecdca4c2f2c4128d.png",
      rating: 4.3,
    },
    {
      id: 16,
      name: "BLACK Wide Strap Slip on Sandals",
      category: "Sandals",
      previousPrice: "2880৳",
      price: "2550৳",
      imageSrc: "https://i.ibb.co/TKwQ9DF/handmade-leather-wide-strap-slip.png",
      rating: 3.9,
    },
    {
      id: 17,
      name: "Bag Leather Duffel Travel Men",
      category: "Bags",
      previousPrice: "3350৳",
      price: "3100৳",
      imageSrc: "https://i.ibb.co/ScWTt3K/images-1.png",
      rating: 4.0,
    },
    {
      id: 18,
      name: "Ultra Premium Wallet",
      category: "Wallets",
      previousPrice: "3900৳",
      price: "3550৳",
      imageSrc:
        "https://i.ibb.co/TLP8BY1/O1-CN01-Kaj-Xi32-Lx-Ddxv-Rj-Rk-28498897.png",
      rating: 4.8,
    },
    {
      id: 19,
      name: "Cartelo Branded Leather Belt",
      category: "Belt",
      previousPrice: "400৳",
      price: "329৳",
      imageSrc: "https://i.ibb.co/dLZWkZh/15-1.png",
      rating: 4.5,
    },
    {
      id: 20,
      name: "Pink Sneakers For women For Casual use",
      category: "Shoes",
      previousPrice: "2010৳",
      price: "1650৳",
      imageSrc: "https://i.ibb.co/xsXYzkd/7592d001b3a88fb8be1172ba44419840.png",
      rating: 4.1,
    },
    {
      id: 21,
      name: "BENI BELT",
      category: "Belt",
      previousPrice: "1250৳",
      price: "1190৳",
      imageSrc: "https://i.ibb.co/xMQ9vCQ/S0206c0a1b9954baa9ff27c37444aa0c.png",
      rating: 4.2,
    },
    {
      id: 22,
      name: "EF smart ladies heels sandal",
      category: "Sandals",
      previousPrice: "370৳",
      price: "290৳",
      imageSrc: "https://i.ibb.co/1RhNVHV/1c4417baedaa5dde1eeea989b3ac6501.png",
      rating: 4.3,
    },
    {
      id: 23,
      name: "Cow Leather Laptop Bag SB-LB454",
      category: "Bags",
      previousPrice: "4950৳",
      price: "4550৳",
      imageSrc: "https://i.ibb.co/7z2hxY2/Cow-Leather-Laptop-Bag-SB-LB454.png",
      rating: 4.0,
    },
    {
      id: 24,
      name: "ORAS Genuine Leather Ladies Purse",
      category: "Wallets",
      previousPrice: "1399৳",
      price: "1299৳",
      imageSrc: "https://i.ibb.co/fDMTzqB/RA69-M-3-510x510.png",
      rating: 4.7,
    },
    {
      id: 25,
      name: "Genuine-leather-loafer",
      category: "Loafers",
      previousPrice: "2410৳",
      price: "2150৳",
      imageSrc: "https://i.ibb.co/Yjp7yZL/genuine-leather-loafer-for-men-l.png",
      rating: 4.4,
    },
    {
      id: 26,
      name: "Leather formal Belt for Men Black",
      category: "Belt",
      previousPrice: "750৳",
      price: "550৳",
      imageSrc: "https://i.ibb.co/r3DrYSw/6ba346ddda04a2745921f1d2f811dfbf.png",
      rating: 3.5,
    },
    {
      id: 27,
      name: "Leather-Mens-Leather-Sandal",
      category: "Sandals",
      previousPrice: "1110৳",
      price: "999৳",
      imageSrc: "https://i.ibb.co/MRMHvBf/SSB-Leather-Mens-Leather-Sandal.png",
      rating: 4.9,
    },
    {
      id: 28,
      name: "Classic Backpack SB-BP138",
      category: "Bags",
      previousPrice: "7950৳",
      price: "7450৳",
      imageSrc: "https://i.ibb.co/NyBhYjz/Classic-Backpack-SB-BP138.png",
      rating: 3.7,
    },
    {
      id: 29,
      name: "The Seiko Alpinist SPB117 - 9GAG",
      category: "Watch",
      previousPrice: "1620৳",
      price: "1440৳",
      imageSrc: "https://i.ibb.co/bbrRD27/a-R7-Rob-M-460s.png",
      rating: 4.5,
    },
    {
      id: 30,
      name: "Mens-Leather-Executive-Bag",
      category: "Bags",
      previousPrice: "6320৳",
      price: "5999৳",
      imageSrc: "https://i.ibb.co/9vGxKRR/Mens-Leather-Executive-Bag-SB-LB.png",
      rating: 4.1,
    },

    {
      id: 31,
      name: "PATENT TASSEL MOCCASINS",
      category: "Shoes",
      previousPrice: "4000৳",
      price: "3499৳",
      imageSrc: "https://i.ibb.co/znbwc3R/938190014499-A-700x.png",
      rating: 4.2,
    },

    {
      id: 32,
      name: "Amber-Padded-Italian",
      category: "Watch",
      previousPrice: "1990৳",
      price: "1899৳",
      imageSrc: "https://i.ibb.co/yyXJ0hz/20mm-Amber-Padded-Italian-Vintag.png",
      rating: 4.2,
    },
    {
      id: 33,
      name: "Brown Leather Formal Belt For Men",
      category: "Belt",
      previousPrice: "320৳",
      price: "250৳",
      imageSrc: "https://i.ibb.co/6vmcRLb/b7feff36334be47319a971caedc40cb5.jpg",
      rating: 3.8,
    },
    {
      id: 34,
      name: "Mens-Leather-Sandal",
      category: "Sandals",
      previousPrice: "910৳",
      price: "799৳",
      imageSrc: "https://i.ibb.co/p4Vb2RT/Mens-Leather-Sandal-SB-S528-3.png",
      rating: 4.1,
    },
    {
      id: 35,
      name: "Black Plane Leather Executive Bag SB-LB442",
      category: "Bags",
      previousPrice: "6320৳",
      price: "5999৳",
      imageSrc: "https://i.ibb.co/DtMNw7Q/Black-Plane-Leather-Executive-Ba.png",
      rating: 4.6,
    },
    {
      id: 36,
      name: "Fossil Townsman Men's Watch with Chronograph Display and Genuine Leather Band",
      category: "Watch",
      previousPrice: "3800৳",
      price: "3499৳",
      imageSrc: "https://i.ibb.co/5vvcwq7/71b5-Mt-Bv-L6-L-AC-UL320.png",
      rating: 3.5,
    },
    {
      id: 37,
      name: "CURREN 8314 Casual Waterproof Watch",
      category: "Watch",
      previousPrice: "1290৳",
      price: "1199৳",
      imageSrc: "https://i.ibb.co/JcP0Qcz/CURREN-8314-Casual-Waterproof-Wa.png",
      rating: 4.3,
    },
    {
      id: 38,
      name: "Premium-Leather-Slip-On-Shoe",
      category: "Shoes",
      previousPrice: "1700৳",
      price: "1599৳",
      imageSrc: "https://i.ibb.co/9nLHQzW/AAJ-Premium-Leather-Slip-On-Shoe.png",
      rating: 3.9,
    },
    {
      id: 39,
      name: "Islamic Silicone Bracelet",
      category: "Bracelet",
      previousPrice: "350৳",
      price: "299৳",
      imageSrc: "https://i.ibb.co/hRtYpr9/C183-1-247x247.png",
      rating: 4.0,
    },
    {
      id: 40,
      name: "Product 51",
      category: "Sandals",
      previousPrice: "380৳",
      price: "330৳",
      imageSrc: "https://i.ibb.co/p4Vb2RT/Mens-Leather-Sandal-SB-S528-3.png",
      rating: 4.8,
    },
    {
      id: 41,
      name: "PLAIN LOAFERS",
      category: "Loafers",
      previousPrice: "3190৳",
      price: "2815৳",
      imageSrc: "https://i.ibb.co/LCQ60Jc/custom-resized-4082d9a2-d40e-454.png",
      rating: 3.7,
    },
    {
      id: 42,
      name: "SSB Leather GYM Bag SB-GM02",
      category: "Bags",
      previousPrice: "5890৳",
      price: "5599৳",
      imageSrc: "https://i.ibb.co/vQwY4sm/SSB-Leather-GYM-Bag-SB-GM02-A.png",
      rating: 3.6,
    },
    {
      id: 43,
      name: "Black-Leather-Wallet",
      category: "Wallets",
      previousPrice: "820৳",
      price: "650৳",
      imageSrc: "https://i.ibb.co/Gdj1YLB/Black-Leather-Card-Holder-SB-W12.png",
      rating: 4.5,
    },
    {
      id: 44,
      name: "Maroon-Gradient-Messenger-Bag",
      category: "Bags",
      previousPrice: "4100৳",
      price: "3999৳",
      imageSrc: "https://i.ibb.co/PxQzBgZ/Maroon-Gradient-Messenger-Bag-SB.png",
      rating: 4.3,
    },
    {
      id: 45,
      name: "CURREN-R2-S-Unisex-Smartwatch",
      category: "Watch",
      previousPrice: "1900৳",
      price: "1799৳",
      imageSrc:
        "https://i.ibb.co/wgMmNVj/CURREN-R2-S-Unisex-Smartwatch-IP6.png",
      rating: 4.7,
    },
    {
      id: 46,
      name: "Set Vintage hand-woven Bracelet for Men",
      category: "Bracelet",
      previousPrice: "590৳",
      price: "499৳",
      imageSrc: "https://i.ibb.co/YcyFnfB/C139-510x510.png",
      rating: 4.2,
    },
    {
      id: 47,
      name: "AUTOGRAPH LEO W",
      category: "Shoes",
      previousPrice: "3190৳",
      price: "2999৳",
      imageSrc: "https://i.ibb.co/3pCdwRq/219587-1-PL-01.png",
      rating: 4.9,
    },
    {
      id: 48,
      name: "Floral Design Ladies Handbag SB-HB539",
      category: "Bags",
      previousPrice: "4000৳",
      price: "3699৳",
      imageSrc: "https://i.ibb.co/rt4YP21/2-1.png",
      rating: 3.7,
    },
    {
      id: 49,
      name: "PLAIN HALF LOAFERS",
      category: "Loafers",
      previousPrice: "6550৳",
      price: "6290৳",
      imageSrc: "https://i.ibb.co/6BGg0Ht/130-736ad026-971e-49c5-87fb-ae57.png",
      rating: 4.6,
    },
    {
      id: 50,
      name: "Set Vintage hand-woven Bracelet for Men",
      category: "Bracelet",
      previousPrice: "500৳",
      price: "450৳",
      imageSrc: "https://i.ibb.co/2qjHPtT/C136-510x508.png",
      rating: 3.8,
    },
    {
      id: 51,
      name: "Men's Navy Multi-Sport Jacket",
      category: "Jacket",
      previousPrice: "3200৳",
      price: "2999৳",
      imageSrc: "https://i.ibb.co/ccVnwzw/217364-1-CI-0979.png",
      rating: 4.6,
    },
    {
      id: 52,
      name: "Set believe rope retro braided Bracelet for Men",
      category: "Bracelet",
      previousPrice: "650৳",
      price: "599৳",
      imageSrc: "https://i.ibb.co/8XHW5G6/C132-510x510.png",
      rating: 4.0,
    },
    {
      id: 53,
      name: "Oxford Whole Cut Shoes",
      category: "Shoes",
      previousPrice: "5200৳",
      price: "4990৳",
      imageSrc:
        "https://i.ibb.co/wQ0xVGd/128-8c19efb6-491d-4b58-84c4-af3e-1.png",
      rating: 3.8,
    },
    {
      id: 54,
      name: "Canvas Hot Tactical Casual Plastic Black Buckle",
      category: "Belt",
      previousPrice: "440৳",
      price: "399৳",
      imageSrc: "https://i.ibb.co/3hkCQPV/edc8dc98da3d5ca89d3a89085332f12b.png",
      rating: 3.9,
    },
    {
      id: 55,
      name: "Mens-Leather-Sandal",
      category: "Sandals",
      previousPrice: "990৳",
      price: "899৳",
      imageSrc: "https://i.ibb.co/sFm4zRW/Mens-Leather-Sandal-SB-S528-2.png",
      rating: 4.1,
    },
    {
      id: 56,
      name: "Distressed-Leather-Duffle-Bag",
      category: "Bags",
      previousPrice: "10590৳",
      price: "9999৳",
      imageSrc: "https://i.ibb.co/Y45FNFw/Distressed-Leather-Duffle-Bag-SB.png",
      rating: 4.5,
    },
    {
      id: 57,
      name: "Antique Brown ( Agun ) Short Leather Wallet",
      category: "Wallets",
      previousPrice: "1120৳",
      price: "999৳",
      imageSrc: "https://i.ibb.co/GtS8BG9/Antique-Brown-Agun-Short-Leather.png",
      rating: 3.5,
    },
    {
      id: 58,
      name: "Brown PU Lather Jacket For Men",
      category: "Jacket",
      previousPrice: "1710৳",
      price: "1599৳",
      imageSrc: "https://i.ibb.co/PQ7j9w3/6c0a9804afd778d0e01ca1fc6ba4f39c.png",
      rating: 4.4,
    },
    {
      id: 59,
      name: "TRENDY LOAFER",
      category: "Loafers",
      previousPrice: "880৳",
      price: "790৳",
      imageSrc:
        "https://i.ibb.co/w4rPRbQ/902690113199-DS-07571dba-53a5-488.png",
      rating: 4.5,
    },
    {
      id: 60,
      name: " Handmade Biblical Leather Sandals",
      category: "Sandals",
      previousPrice: "3700৳",
      price: "3499৳",
      imageSrc: "https://i.ibb.co/hWxZM8D/images-2.png",
      rating: 4.7,
    },

    {
      id: 61,
      name: "BUCKLED LOAFER",
      category: "Shoes",
      previousPrice: "3650৳",
      price: "3250৳",
      imageSrc: "https://i.ibb.co/DYbX3LY/157-700x.png",
      rating: 4.3,
    },

    {
      id: 62,
      name: "Front Adjustable Sandals",
      category: "Sandals",
      previousPrice: "3300৳",
      price: "2299৳",
      imageSrc: "https://i.ibb.co/R6RqPkc/x-strap-front-adjustable-handmad.png",
      rating: 3.8,
    },
    {
      id: 63,
      name: "Multifunctional Long Leather Wallet",
      category: "Wallets",
      previousPrice: "1700৳",
      price: "1499৳",
      imageSrc: "https://i.ibb.co/T2B5LjL/Multifunctional-Long-Leather-Wal.png",
      rating: 4.1,
    },

    {
      id: 64,
      name: "lotto-black-neL",
      category: "Shoes",
      previousPrice: "3900৳",
      price: "3499৳",
      imageSrc: "https://i.ibb.co/9cZQZ1T/7-f21r5759-070-7-lotto-black-neo.png",
      rating: 4.0,
    },
    {
      id: 65,
      name: "White-Plaited-Leather-Belt",
      category: "Belt",
      previousPrice: "1600৳",
      price: "1499৳",
      imageSrc: "https://i.ibb.co/x56Prsg/White-Plaited-Leather-Belt-SB-B6.png",
      rating: 4.4,
    },
    {
      id: 66,
      name: "PREMIUM LEATHER FORMALS",
      category: "Shoes",
      previousPrice: "5320৳",
      price: "4990৳",
      imageSrc: "https://i.ibb.co/LkVJs2Q/935190035999-A-700x.png",
      rating: 3.9,
    },
    {
      id: 67,
      name: "Plaited-Leather-Belt",
      category: "Belt",
      previousPrice: "1610৳",
      price: "1549৳",
      imageSrc: "https://i.ibb.co/QcmJVRw/Plaited-Leather-Belt-SB-B66-4.png",
      rating: 4.8,
    },
    {
      id: 68,
      name: "EMBOSSED OXFORD SHOES",
      category: "Shoes",
      previousPrice: "2490৳",
      price: "2170৳",
      imageSrc: "https://i.ibb.co/gdgKT5Z/918190233499-A-700x.png",
      rating: 4.7,
    },
    {
      id: 69,
      name: "VIBRANT CRYSTAL ORCHID LADIES SUMMER",
      category: "Sandals",
      previousPrice: "1450৳",
      price: "1299৳",
      imageSrc: "https://i.ibb.co/vv0Zxpx/5405013-7-500x.png",
      rating: 3.6,
    },
    {
      id: 70,
      name: "Black-Leather-Tote-Bag",
      category: "Bags",
      previousPrice: "3890৳",
      price: "3499৳",
      imageSrc: "https://i.ibb.co/cLKKZwD/Black-Leather-Tote-Bag-SB-LG208.png",
      rating: 4.1,
    },
    {
      id: 71,
      name: "MEN COMFY WALK LEATHER TOEPOST",
      category: "Shoes",
      previousPrice: "1920৳",
      price: "1699৳",
      imageSrc: "https://i.ibb.co/2SZ0N1z/84460241-500x.png",
      rating: 4.9,
    },
    {
      id: 72,
      name: "MEN LEATHER GEAR BELT",
      category: "Belt",
      previousPrice: "790৳",
      price: "699৳",
      imageSrc: "https://i.ibb.co/qxnHKRy/93450432-500x.png",
      rating: 4.7,
    },
    {
      id: 73,
      name: "Lightweight Outdoors For Men  (Olive)",
      category: "Shoes",
      previousPrice: "2510৳",
      price: "2299৳",
      imageSrc: "https://i.ibb.co/WgHY5z9/6-faf4-6-furo-olive-original-ima.png",
      rating: 4.2,
    },
    {
      id: 74,
      name: "Genuine Leather Belt for Men",
      category: "Belt",
      previousPrice: "580৳",
      price: "499৳",
      imageSrc: "https://i.ibb.co/XbJnCR0/b164-1-510x510.png",
      rating: 3.8,
    },
    {
      id: 75,
      name: "MC3 Megir Blue Chronograph",
      category: "Watch",
      previousPrice: "3200৳",
      price: "3099৳",
      imageSrc: "https://i.ibb.co/FHtPX4F/MC3-510x510.png",
      rating: 4.6,
    },
    {
      id: 76,
      name: "Genuine-Leather-Executive-Bag",
      category: "Bags",
      previousPrice: "8000৳",
      price: "7699৳",
      imageSrc: "https://i.ibb.co/jg24VTq/Genuine-Leather-Executive-Bag-SB.png",
      rating: 4.5,
    },
    {
      id: 77,
      name: "WA85N JEEP Genuine Leather Wallet",
      category: "Wallets",
      previousPrice: "1460৳",
      price: "1300৳",
      imageSrc: "https://i.ibb.co/mXKS5d1/WA85-N-2-510x510.png",
      rating: 4.0,
    },
    {
      id: 78,
      name: "EMBOSSED OXFORD SHOES",
      category: "Shoes",
      previousPrice: "5200৳",
      price: "4950৳",
      imageSrc: "https://i.ibb.co/kxq885Y/118-2ebfee83-14c6-4ae8-9aab-691d.png",
      rating: 3.5,
    },

    {
      id: 79,
      name: "Plain Loafers",
      category: "Loafers",
      previousPrice: "1600৳",
      price: "1559৳",
      imageSrc: "https://i.ibb.co/52CZp7w/150-700x.png",
      rating: 4.4,
    },
    {
      id: 80,
      name: "Men’s Breathable Running Shoes: White Mesh Casual Sneakers",
      category: "Shoes",
      previousPrice: "3100৳",
      price: "2799৳",
      imageSrc: "https://i.ibb.co/mcbk558/Z1013-5-510x510.png",
      rating: 4.4,
    },
    {
      id: 81,
      name: "Aaj-Leather-Executive-Bag",
      category: "Bags",
      previousPrice: "5510৳",
      price: "5299৳",
      imageSrc: "https://i.ibb.co/jZtgQ7n/Aaj-Leather-Executive-Bag-SB-LB4.png",
      rating: 4.6,
    },
    {
      id: 82,
      name: "PREMIUM LEATHER FORMALS",
      category: "Shoes",
      previousPrice: "5230৳",
      price: "4999৳",
      imageSrc: "https://i.ibb.co/F7ktYRW/934190035999-ST-600x.png",
      rating: 4.1,
    },
    {
      id: 83,
      name: "Oil-Pull-Up-Leather-Duffle-Bag",
      category: "Bags",
      previousPrice: "12320৳",
      price: "11990৳",
      imageSrc: "https://i.ibb.co/RYJx1FH/Oil-Pull-Up-Leather-Duffle-Bag-S.png",
      rating: 4.7,
    },
    {
      id: 84,
      name: "Leather Jacket for men",
      category: "Jacket",
      previousPrice: "7500৳",
      price: "7100৳",
      imageSrc: "https://i.ibb.co/bNZ640v/samo-puja-2023-ot-26-9b05.png",
      rating: 3.6,
    },
  ];
};

export default CardData;
